package eo;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 05 21:11:48 AST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DoctorsImpl extends EntityImpl {
    /**
     * Validation method for Location.
     */
    public boolean validateLocation(String location) {
        if(location.contains("$") || location.contains("#"))
            return false;
        return true;
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DoctorId,
        Name,
        Specialty,
        Location,
        Gender,
        Appointments;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DOCTORID = AttributesEnum.DoctorId.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int SPECIALTY = AttributesEnum.Specialty.index();
    public static final int LOCATION = AttributesEnum.Location.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int APPOINTMENTS = AttributesEnum.Appointments.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DoctorsImpl() {
    }

    /**
     * @param doctorId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long doctorId) {
        return new Key(new Object[] { doctorId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("eo.Doctors");
    }


}

